#pragma once
#include "../../hardware/hardware.h"
#include "../../x86-64/pic/8259_pic.h"
#include "../../x86-64/stdio/stdio.h"
#include "../../x86-64/applications/terminal.h"

typedef enum {
  SC_ESC        = 0x01,
  SC_1          = 0x02,
  SC_2          = 0x03,
  SC_3          = 0x04,
  SC_4          = 0x05,
  SC_5          = 0x06,
  SC_6          = 0x07,
  SC_7          = 0x08,
  SC_8          = 0x09,
  SC_9          = 0x0A,
  SC_0          = 0x0B,
  SC_MINUS      = 0x0C,
  SC_EQUAL      = 0x0D,
  SC_BACKSPACE  = 0x0E,
  SC_TAB        = 0x0F,

  SC_Q          = 0x10,
  SC_W          = 0x11,
  SC_E          = 0x12,
  SC_R          = 0x13,
  SC_T          = 0x14,
  SC_Y          = 0x15,
  SC_U          = 0x16,
  SC_I          = 0x17,
  SC_O          = 0x18,
  SC_P          = 0x19,
  SC_LBRACKET   = 0x1A,
  SC_RBRACKET   = 0x1B,
  SC_ENTER      = 0x1C,

  SC_LCTRL      = 0x1D,
  SC_A          = 0x1E,
  SC_S          = 0x1F,
  SC_D          = 0x20,
  SC_F          = 0x21,
  SC_G          = 0x22,
  SC_H          = 0x23,
  SC_J          = 0x24,
  SC_K          = 0x25,
  SC_L          = 0x26,
  SC_SEMICOLON  = 0x27,
  SC_APOSTROPHE = 0x28,
  SC_GRAVE      = 0x29,

  SC_LSHIFT     = 0x2A,
  SC_BACKSLASH  = 0x2B,
  SC_Z          = 0x2C,
  SC_X          = 0x2D,
  SC_C          = 0x2E,
  SC_V          = 0x2F,
  SC_B          = 0x30,
  SC_N          = 0x31,
  SC_M          = 0x32,
  SC_COMMA      = 0x33,
  SC_DOT        = 0x34,
  SC_SLASH      = 0x35,
  SC_RSHIFT     = 0x36,

  SC_KP_ASTERISK= 0x37,
  SC_LALT       = 0x38,
  SC_SPACE      = 0x39,
  SC_CAPSLOCK   = 0x3A,

  SC_F1         = 0x3B,
  SC_F2         = 0x3C,
  SC_F3         = 0x3D,
  SC_F4         = 0x3E,
  SC_F5         = 0x3F,
  SC_F6         = 0x40,
  SC_F7         = 0x41,
  SC_F8         = 0x42,
  SC_F9         = 0x43,
  SC_F10        = 0x44,

  SC_NUMLOCK    = 0x45,
  SC_SCROLLLOCK = 0x46,

  SC_KP_7       = 0x47,
  SC_KP_8       = 0x48,
  SC_KP_9       = 0x49,
  SC_KP_MINUS   = 0x4A,
  SC_KP_4       = 0x4B,
  SC_KP_5       = 0x4C,
  SC_KP_6       = 0x4D,
  SC_KP_PLUS    = 0x4E,
  SC_KP_1       = 0x4F,
  SC_KP_2       = 0x50,
  SC_KP_3       = 0x51,
  SC_KP_0       = 0x52,
  SC_KP_DOT     = 0x53,

  SC_E0_HOME        = 0x47,
  SC_E0_UP          = 0x48,
  SC_E0_PAGEUP      = 0x49,
  SC_E0_LEFT        = 0x4B,
  SC_E0_RIGHT       = 0x4D,
  SC_E0_END         = 0x4F,
  SC_E0_DOWN        = 0x50,
  SC_E0_PAGEDOWN    = 0x51,
  SC_E0_INSERT      = 0x52,
  SC_E0_DELETE      = 0x53,

  SC_E0_RCTRL       = 0x1D,
  SC_E0_RALT        = 0x38,
} ScanCode;

typedef enum {
  KEY_NONE            = 0,
  KEY_A               = 30,
  KEY_B               = 48,
  KEY_C               = 46,
  KEY_D               = 32,
  KEY_E               = 18,
  KEY_F               = 33,
  KEY_G               = 34,
  KEY_H               = 35,
  KEY_I               = 23,
  KEY_J               = 36,
  KEY_K               = 37,
  KEY_L               = 38,
  KEY_M               = 50,
  KEY_N               = 49,
  KEY_O               = 24,
  KEY_P               = 25,
  KEY_Q               = 16,
  KEY_R               = 19,
  KEY_S               = 31,
  KEY_T               = 20,
  KEY_U               = 22,
  KEY_V               = 47,
  KEY_W               = 17,
  KEY_X               = 45,
  KEY_Y               = 21,
  KEY_Z               = 44,
  KEY_1               = 2,
  KEY_2               = 3,
  KEY_3               = 4,
  KEY_4               = 5,
  KEY_5               = 6,
  KEY_6               = 7,
  KEY_7               = 8,
  KEY_8               = 9,
  KEY_9               = 10,
  KEY_0               = 11,
  KEY_MINUS           = 12,
  KEY_EQUAL           = 13,
  KEY_LEFTBRACE       = 26,
  KEY_RIGHTBRACE      = 27,
  KEY_BACKSLASH       = 43,
  KEY_SEMICOLON       = 39,
  KEY_APOSTROPHE      = 40,
  KEY_GRAVE           = 41,
  KEY_COMMA           = 51,
  KEY_DOT             = 52,
  KEY_SLASH           = 53,
  KEY_ENTER           = 28,
  KEY_BACKSPACE       = 14,
  KEY_TAB             = 15,
  KEY_SPACE           = 57,
  KEY_ESC             = 1,
  KEY_LEFTSHIFT       = 42,
  KEY_RIGHTSHIFT      = 54,
  KEY_LEFTCTRL        = 29,
  KEY_RIGHTCTRL       = 97,
  KEY_LEFTALT         = 56,
  KEY_RIGHTALT        = 100,
  KEY_CAPSLOCK        = 58,
  KEY_F1              = 59,
  KEY_F2              = 60,
  KEY_F3              = 61,
  KEY_F4              = 62,
  KEY_F5              = 63,
  KEY_F6              = 64,
  KEY_F7              = 65,
  KEY_F8              = 66,
  KEY_F9              = 67,
  KEY_F10             = 68,
  KEY_F11             = 87,
  KEY_F12             = 88,

  /* ===== Navigation ===== */
  KEY_UP              = 103,
  KEY_DOWN            = 108,
  KEY_LEFT            = 105,
  KEY_RIGHT           = 106,
  KEY_HOME            = 102,
  KEY_END             = 107,
  KEY_PAGEUP          = 104,
  KEY_PAGEDOWN        = 109,
  KEY_INSERT          = 110,
  KEY_DELETE          = 111,

  /* ===== Numpad ===== */
  KEY_NUMLOCK         = 69,
  KEY_KP_DIVIDE       = 98,
  KEY_KP_MULTIPLY     = 55,
  KEY_KP_MINUS        = 74,
  KEY_KP_PLUS         = 78,
  KEY_KP_ENTER        = 96,

  KEY_KP_1            = 79,
  KEY_KP_2            = 80,
  KEY_KP_3            = 81,
  KEY_KP_4            = 75,
  KEY_KP_5            = 76,
  KEY_KP_6            = 77,
  KEY_KP_7            = 71,
  KEY_KP_8            = 72,
  KEY_KP_9            = 73,
  KEY_KP_0            = 82,
  KEY_KP_DOT          = 83,

  /* ===== System ===== */
  KEY_SCROLLLOCK      = 70,
  KEY_PAUSE           = 119,
  KEY_PRINTSCREEN     = 99,

  KEY_MAX             = 256
} Key;


struct key_event {
  Key key;
  bool pressed;
};


char translate_keycode_to_asci(Key key);
void handle_keyboard_interrupt();
struct key_event translate_scancode(uint8_t scancode);

